version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"

  # Enable version updates for NuGet
  - package-ecosystem: "nuget"
    directory: "/src" # Check the src directory for .NET project files
    schedule:
      interval: "weekly"
    # Group all nuget updates into a single PR
    groups:
      nuget-updates:
        patterns:
          - "*"

  - package-ecosystem: "dotnet-sdk"
    directory: "/src" # Check the src directory for .NET project files
    schedule:
      interval: "weekly"
    # Group all nuget updates into a single PR
    groups:
      all-dotnet-sdk:
        patterns:
          - "*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Following the docs https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
    schedule:
      interval: "weekly"
    # Group all GitHub Actions updates into a single PR
    groups:
      actions-updates:
        patterns:
          - "*"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directories: 
      - "/src/BlazorPong.SignalR" # Dockerfile in BlazorPong.SignalR
      - "/src/BlazorPong.Web/Server" # Dockerfile in BlazorPong.Web/Server
    schedule:
      interval: "weekly"
    groups:
      docker-updates: # Group Docker updates
        patterns:
          - "*"
