version: 2
updates:
  # Enable version updates for NuGet
  - package-ecosystem: "nuget"
    directory: "/src" # Check the src directory for .NET project files
    schedule:
      interval: "daily"
    # Group all nuget updates into a single PR
    groups:
      nuget-updates:
        patterns:
          - "*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows" # Check the .github/workflows directory
    schedule:
      interval: "daily"
    # Group all GitHub Actions updates into a single PR
    groups:
      actions-updates:
        patterns:
          - "*"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/src" # Check for Dockerfiles in the src directory and subdirectories
    schedule:
      interval: "daily"
    # Group all Docker updates into a single PR
    groups:
      docker-updates:
        patterns:
          - "*"
