apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f src/docker-compose.nobuild.yml --volumes emptyDir -o src/infra/aks
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: azuresql
  name: azuresql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: azuresql
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f src/docker-compose.nobuild.yml --volumes emptyDir -o src/infra/aks
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: azuresql
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              value: yourStrong(!)Password
          image: mcr.microsoft.com/mssql/server:2025-latest
          livenessProbe:
            exec:
              command:
                - /opt/mssql-tools/bin/sqlcmd -S localhost -C -U sa -P "$MSSQL_SA_PASSWORD" -Q "select 1"
            failureThreshold: 10
            periodSeconds: 3
            timeoutSeconds: 1
          name: azuresql
          ports:
            - containerPort: 1433
              protocol: TCP
      hostname: azuresql
      restartPolicy: Always
