apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f src/docker-compose.nobuild.yml --volumes emptyDir -o src/infra/aks
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: collector
  name: collector
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: collector
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f src/docker-compose.nobuild.yml --volumes emptyDir -o src/infra/aks
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: collector
    spec:
      containers:
        - args:
            - --config=/shared/cloudnativeblazorpong/src/Observability/otel-collector-config.yaml
          image: otel/opentelemetry-collector-contrib:latest
          name: collector
          ports:
            - containerPort: 4317
              protocol: TCP
            - containerPort: 4318
              protocol: TCP
            - containerPort: 8889
              protocol: TCP
          volumeMounts:
            - mountPath: /shared
              name: repo
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: repo
