apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f src/docker-compose.nobuild.yml --volumes emptyDir -o src/infra/aks
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: signalr
  name: signalr
spec:
  ports:
    - name: "6351"
      port: 6351
      targetPort: 8080
    - name: "6402"
      port: 6402
      targetPort: 9090
  selector:
    io.kompose.service: signalr
