apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f src/docker-compose.nobuild.yml --volumes emptyDir -o src/infra/aks
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: signalr
  name: signalr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: signalr
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f src/docker-compose.nobuild.yml --volumes emptyDir -o src/infra/aks
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: signalr
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__AzureSql
              value: Server=azuresql;Database=BlazorpongDB;User=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;Encrypt=False;
            - name: ConnectionStrings__Redis
              value: redis:6379
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://collector:4317
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=signalr
          image: ghcr.io/macel94/cloudnativeblazorpong/blazorpong-signalr:latest
          name: signalr
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9090
              protocol: TCP
      restartPolicy: Always
