apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f src/docker-compose.nobuild.yml --volumes emptyDir -o src/infra/aks
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: webapp
  name: webapp
spec:
  ports:
    - name: "6350"
      port: 6350
      targetPort: 8080
    - name: "6401"
      port: 6401
      targetPort: 9090
  selector:
    io.kompose.service: webapp
