global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: signalr
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - signalr:9090

  - job_name: webapp
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - webapp:9090
  
  - job_name: tempo
    static_configs:
      - targets: [ 'tempo:3200' ]