global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  # - job_name: tempo
  #   static_configs:
  #     - targets: [ 'tempo:3200' ]
  - job_name: collector
    static_configs:
      - targets: [ 'collector:8889' ]