#FROM mcr.microsoft.com/azure-sql-edge:latest
#
#WORKDIR /src
#COPY ["Blazorpong.Database.AzureSql/Snapshots/v0.dacpac", "v0.dacpac"]
#COPY ["Blazorpong.Database.AzureSql/Scripts/deploy-dacpac.sh", "deploy-dacpac.sh"]
#
## # Copy the deployment script to the container
#RUN chmod +x /deploy-dacpac.sh
#
## # Set the entry point to execute the deployment script
#ENTRYPOINT ["/deploy-dacpac.sh"]



# continue here: https://learn.microsoft.com/en-us/azure/azure-sql-edge/deploy-dacpac