apiVersion: batch/v1
kind: Job
metadata:
  name: db-init
  namespace: blazorpong
  labels:
    app: db-init
spec:
  backoffLimit: 10
  template:
    metadata:
      labels:
        app: db-init
    spec:
      restartPolicy: OnFailure
      containers:
        - name: db-init
          image: mcr.microsoft.com/mssql/server:2025-latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SA_PASSWORD
              value: "yourStrong(!)Password"
          command:
            - bash
            - -euxc
            - |
              # Wait for SQL Server to be available
              for i in $(seq 1 30); do
                /opt/mssql-tools18/bin/sqlcmd -S azuresql -C -U sa -P "$SA_PASSWORD" -Q "SELECT 1" 2>/dev/null && break
                echo "Waiting for SQL Server... ($i)"
                sleep 5
              done

              # Create database and tables
              /opt/mssql-tools18/bin/sqlcmd -S azuresql -C -U sa -P "$SA_PASSWORD" -Q "
                IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'BlazorpongDB')
                  CREATE DATABASE BlazorpongDB;
              "

              /opt/mssql-tools18/bin/sqlcmd -S azuresql -C -U sa -P "$SA_PASSWORD" -d BlazorpongDB -Q "
                IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'Room')
                  CREATE TABLE [dbo].[Room] (
                    [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
                    [ServerName] NVARCHAR(50) NULL
                  );

                IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'Client')
                  CREATE TABLE [dbo].[Client] (
                    [Username] NVARCHAR(50) NOT NULL,
                    [RoomId] UNIQUEIDENTIFIER NOT NULL,
                    [Role] TINYINT NULL,
                    [ConnectionId] NVARCHAR(50) NOT NULL,
                    PRIMARY KEY ([Username], [ConnectionId]),
                    FOREIGN KEY ([RoomId]) REFERENCES Room(Id)
                  );
              "

              echo "Database initialization complete!"
