apiVersion: apps/v1
kind: Deployment
metadata:
  name: signalr
  namespace: blazorpong
  labels:
    app: signalr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signalr
  template:
    metadata:
      labels:
        app: signalr
    spec:
      containers:
        - name: signalr
          image: ghcr.io/macel94/cloudnativeblazorpong/blazorpong-signalr:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__Redis
              value: "redis:6379"
            - name: ConnectionStrings__AzureSql
              value: "Server=azuresql;Database=BlazorpongDB;User=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;Encrypt=False;"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://collector:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=signalr
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: signalr
  namespace: blazorpong
  labels:
    app: signalr
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: signalr
