apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: blazorpong
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: ghcr.io/macel94/cloudnativeblazorpong/blazorpong-web:latest
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
              value: "true"
            - name: GameHubEndpoint
              value: "http://localhost:8080/gamehub"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://collector:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=webapp
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: blazorpong
  labels:
    app: webapp
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: webapp
