apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\FrancescoBelacca\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -c -f C:\Users\FrancescoBelacca\source\repos\cloudnativeblazorpong\src\docker-compose.yml -o .
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: azuresql
  name: azuresql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: azuresql
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\FrancescoBelacca\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -c -f C:\Users\FrancescoBelacca\source\repos\cloudnativeblazorpong\src\docker-compose.yml -o .
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/src-default: "true"
        io.kompose.service: azuresql
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PACKAGE
              value: /backup/v0.dacpac
            - name: MSSQL_PID
              value: Developer
            - name: MSSQL_SA_PASSWORD
              value: yourStrong(!)Password
          image: mcr.microsoft.com/azure-sql-edge:latest
          name: azuresql
          ports:
            - containerPort: 1433
              hostPort: 1433
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
