apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f ./src/docker-compose.yml -o ./deploy/charts
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: webapp
  name: webapp
spec:
  ports:
    - name: "6350"
      port: 6350
      targetPort: 8080
    - name: "6401"
      port: 6401
      targetPort: 9090
  selector:
    io.kompose.service: webapp
