version: '3.8'

services:
  blazorpong.web.server.1:
    image: ${DOCKER_REGISTRY-}blazorpongwebserver
    build:
      context: .
      dockerfile: BlazorPong.Web/Server/Dockerfile
  blazorpong.web.server.2:
    image: ${DOCKER_REGISTRY-}blazorpongwebserver
    build:
      context: .
      dockerfile: BlazorPong.Web/Server/Dockerfile