version: '3.8'

services:
  webapp:
    image: ${DOCKER_REGISTRY-}blazorpongwebserver
    build:
      context: .
      dockerfile: BlazorPong.Web/Server/Dockerfile

  signalr:
    image: ${DOCKER_REGISTRY-}blazorpongsignalr
    build:
      context: .
      dockerfile: BlazorPong.SignalR/Dockerfile

  signalr-dapr:
    image: "daprio/daprd:latest"
    depends_on:
      - signalr

  redis:
    image: "redis:latest"

  azuresql:
    image: "mcr.microsoft.com/azure-sql-edge:latest"

  dapr-dashboard:
    image: "daprio/dashboard:latest"