version: '3.8'

services:
  blazorpong.web.server.1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Redis=redis:6379
    ports:
      - "6350:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    depends_on:
      - redis
  # blazorpong.web.server.2:
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=8080
  #     - ConnectionStrings__Redis=redis:6379
  #   ports:
  #     - "6351:8080"
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #   depends_on:
  #     - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"