version: '3.8'

services:
  webapp:
    image: ${DOCKER_REGISTRY-}blazorpongwebserver
    build:
      context: .
      dockerfile: BlazorPong.Web/Server/Dockerfile
  signalr:
    image: ${DOCKER_REGISTRY-}blazorpongsignalr
    build:
      context: .
      dockerfile: BlazorPong.SignalR/Dockerfile
  redis:
    image: "redis:latest"
  azuresql:
    image: "mcr.microsoft.com/azure-sql-edge:latest"

  # blazorpong.web.server.2:
  #   image: ${DOCKER_REGISTRY-}blazorpongwebserver
  #   build:
  #     context: .
  #     dockerfile: BlazorPong.Web/Server/Dockerfile