version: '3.8'

services:
  webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GameHubEndpoint=http://localhost:6351/gamehub
    ports:
      - "6350:8080"
    # volumes:
    #   - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    depends_on:
      - signalr

  signalr:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis:6379
      - ConnectionStrings__AzureSql=Server=azuresql;Database=Blazorpong.Database.AzureSql;User=sa;Password=yourStrong(!)Password;TrustServerCertificate=True
    ports:
      - "6351:8080"
    depends_on:
      - redis
      - azuresql

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  
  azuresql:
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    volumes:
      - ./Blazorpong.Database.AzureSql/Snapshots:/backup:ro
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
      - MSSQL_PID=Developer
      - MSSQL_PACKAGE=/backup/v0.dacpac
    ports:
      - "1433:1433"