name: Build and Push Blazorpong Web Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/blazorpong-web.yml'

permissions:
    contents: read
    packages: write
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./src
        file: ./src/BlazorPong.Web/Server/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/blazorpong-web:latest
          ghcr.io/${{ github.repository }}/blazorpong-web:${{ github.sha }}

    # - name: Create GitHub release
    #   id: create_release
    #   uses: actions/create-release@
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
    #   with:
    #     tag_name: ${{ github.ref }}
    #     release_name: Release ${{ github.ref }}
    #     draft: false
    #     prerelease: false